# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-09 21:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170709_2051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='post',
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(related_name='tagged_posts', to='blog.Tag'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='label',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
